import { InvoiceItem, WorkMap, ScreenEvent, DialogueTurn } from '../types/apprentice';

export const INITIAL_INVOICES: InvoiceItem[] = [
  {
    id: 'inv-4471',
    invoiceNumber: 'INV-4471',
    vendor: 'Siemens Precision Tech AG',
    vendorCategory: 'Industrial Machinery',
    amount: 7200.0,
    date: '2026-10-01',
    description: 'Replacement spindle motor for CNC milling line 3',
    currentCostCenter: '4711 • Workshop Operations (Opex)',
    recommendedCostCenter: '0400 • Fixed Assets (Capex)',
    status: 'pending',
    assetNumber: 'AST-9941-DE',
    requiresSecondApproval: false,
    flags: ['Over €5,000'],
    notes: 'Urgent swap out ordered by shop floor.',
  },
  {
    id: 'inv-4472',
    invoiceNumber: 'INV-4472',
    vendor: 'Adolf Würth GmbH',
    vendorCategory: 'Fasteners & Shop Supplies',
    amount: 1240.5,
    date: '2026-10-02',
    description: 'Bulk stainless bolts, cutting fluid, workshop consumables',
    currentCostCenter: '4711 • Workshop Operations (Opex)',
    recommendedCostCenter: '4711 • Workshop Operations (Opex)',
    status: 'pending',
    assetNumber: '',
    requiresSecondApproval: false,
    flags: ['Packing slip attached'],
    notes: 'Regular bi-weekly restock.',
  },
  {
    id: 'inv-4473',
    invoiceNumber: 'INV-4473',
    vendor: 'Delta Logistik GmbH',
    vendorCategory: 'Freight & Haulage',
    amount: 3800.0,
    date: '2026-10-03',
    description: 'Container handling fee - Q4 freight surcharge',
    currentCostCenter: '5200 • Freight & Shipping',
    recommendedCostCenter: '5200 • Freight & Shipping',
    status: 'pending',
    assetNumber: '',
    requiresSecondApproval: true,
    flags: ['December Surcharge'],
    notes: 'Received electronically via carrier EDI.',
  },
];

export const TEACH_MODE_INVOICE: InvoiceItem = {
  id: 'inv-4480',
  invoiceNumber: 'INV-4480',
  vendor: 'DMG MORI Precision Systems',
  vendorCategory: 'Machining Centers',
  amount: 6850.0,
  date: '2026-10-03',
  description: '5-Axis milling tool head upgrade kit',
  currentCostCenter: '4711 • Workshop Operations (Opex)',
  recommendedCostCenter: '0400 • Fixed Assets (Capex)',
  status: 'pending',
  assetNumber: 'AST-8820-ST',
  requiresSecondApproval: false,
  flags: ['Hardware upgrade'],
  notes: 'Requested for bay 4 upgrade.',
};

export const INITIAL_WORK_MAP: WorkMap = {
  id: 'wm-stuttgart-ap-01',
  title: "Sabine's Month-End Invoicing Playbook",
  expertName: 'Sabine Weber',
  expertRole: 'Senior AP Controller (24 years on the job)',
  taskName: 'Supplier Invoice Triage & Cost Center Coding',
  recordedAt: 'Today at 4:10 PM',
  steps: [
    {
      id: 'step-1',
      stepNumber: 1,
      title: 'Check invoice total against the 5k threshold',
      germanTitle: 'Rechnungsbetrag gegen 5.000 € Grenze prüfen',
      screenMoment: {
        timestamp: '01:14',
        uiTarget: 'Invoice header total (€7,200.00)',
        details: 'Looked at line item description: CNC spindle replacement motor.',
      },
      decision: 'Flagged for Capex 0400 re-coding.',
      germanDecision: 'Zur Umbuchung auf Anlagevermögen (0400) markiert.',
      reason: '"Anything over five grand for equipment has to be capitalized for tax depreciation. If you leave it in 4711, plant margins look awful and accounting will chew us out at month-end."',
      germanReason: '"Alles über fünftausend Euro bei Ausrüstung muss steuerlich aktiviert werden. Wenn wir das in 4711 lassen, sieht die Werkstattmarge katastrophal aus und die Buchhaltung steht zum Monatsabschluss auf der Matte."',
      guardrails: [
        'Equipment over €5,000 always goes to Capex 0400.',
        'Must have an asset tag (AST-...) before booking to 0400.',
        'If it is an unknown vendor or has no tag: stop and ping the controller.',
      ],
      germanGuardrails: [
        'Ausrüstung über 5.000 € immer auf 0400 buchen.',
        'Anlagennummer (AST-...) ist vor der Buchung zwingend erforderlich.',
        'Unbekannter Lieferant oder fehlende Nummer: Halt und Rücksprache mit Controller.',
      ],
      confirmedByExpert: true,
    },
    {
      id: 'step-2',
      stepNumber: 2,
      title: 'Switch cost center from 4711 to 0400',
      germanTitle: 'Kostenstelle von 4711 auf 0400 umstellen',
      screenMoment: {
        timestamp: '03:12',
        uiTarget: 'Cost Center dropdown > Selected 0400',
        details: 'Changed default workshop operations code to capital assets.',
      },
      decision: 'Re-coded from opex 4711 to capex 0400 and double-checked the asset tag.',
      germanDecision: 'Von 4711 auf 0400 umkodiert und Anlagennummer geprüft.',
      reason: '"Leaving this in 4711 screws up our plant budget comparison for the whole quarter."',
      germanReason: '"Wenn wir das in 4711 lassen, verzerrt das den gesamten Quartalsvergleich des Werks."',
      guardrails: [
        'Double check the delivery slip matches the asset number.',
        'Capex bookings ping fixed-asset accounting automatically.',
      ],
      confirmedByExpert: true,
    },
    {
      id: 'step-3',
      stepNumber: 3,
      title: 'Approve regular consumable deliveries',
      germanTitle: 'Reguläre Verbrauchsmaterial-Lieferungen freigeben',
      screenMoment: {
        timestamp: '05:30',
        uiTarget: 'Würth invoice > Packing slip PDF',
        details: 'Matched the warehouse delivery slip with the open purchase order.',
      },
      decision: 'Approved under 4711 right away without escalation.',
      germanDecision: 'Direkt unter 4711 ohne Eskalation freigegeben.',
      reason: '"Regular workshop supplies under two grand with matching delivery slips get pushed straight through."',
      germanReason: '"Verbrauchsmaterial unter zweitausend Euro mit passendem Lieferschein geht direkt durch."',
      guardrails: [
        'Always make sure the signed slip is attached.',
        'Supplies over two grand need the shop supervisor to sign off.',
      ],
      confirmedByExpert: true,
    },
    {
      id: 'step-4',
      stepNumber: 4,
      title: 'Freeze Delta Logistik December freight bill',
      germanTitle: 'Delta Logistik Dezember-Frachtrechnung sperren',
      screenMoment: {
        timestamp: '07:45',
        uiTarget: 'Delta Logistik invoice > Hold button',
        details: 'Marked on hold pending year-end carrier reconciliation.',
      },
      decision: 'Froze payment until January reconciliation.',
      germanDecision: 'Zahlung bis zum Januar-Abgleich gesperrt.',
      reason: '"Delta tries to sneak in double charges every single December for container storage. We sit on their freight bills until January so we can square the credits first."',
      germanReason: '"Delta versucht jeden Dezember doppelte Standgelder abzurechnen. Wir stoppen deren Rechnungen grundsätzlich bis zum Januar-Abgleich."',
      guardrails: [
        'Never pay Delta freight invoices in December right off the bat.',
        'Wait for the logistics manager to sign off in January.',
        'Put on administrative hold, do not reject, so we keep the early-pay terms intact.',
      ],
      confirmedByExpert: true,
    },
  ],
  coreGuardrails: [
    'Equipment over €5,000 must be coded to Capex 0400 with a valid asset tag.',
    'No asset tag = no capex booking. Ask the controller first.',
    'Always freeze Delta Logistik December freight bills until January.',
    'Consumables under €2,000 need a verified packing slip before approving.',
  ],
  teachBackSummary:
    "Here is how Sabine handles it: Anything over 5,000 for equipment gets capitalized to 0400 with an asset tag. Regular shop supplies under 2,000 get cleared fast if the slip matches. And Delta Logistik freight in December gets frozen until January reconciliation to avoid duplicate fees.",
  germanTeachBackSummary:
    "Sabines Vorgehen: Ausrüstung über 5.000 € immer auf 0400 mit Anlagennummer aktivieren. Reguläre Lieferungen unter 2.000 € mit Lieferschein direkt freigeben. Delta Logistik Frachtrechnungen im Dezember grundsätzlich bis Januar sperren.",
};

export const INITIAL_DIALOGUE_HISTORY: DialogueTurn[] = [
  {
    id: 'd-1',
    speaker: 'agent',
    persona: 'apprentice',
    text: "Quick question Sabine — why'd you flip Invoice 4471 over to 0400 instead of keeping it in 4711?",
    timestamp: '03:15',
    isGuardrail: true,
    questionContext: 'Cost center switch on €7,200 spindle',
  },
  {
    id: 'd-2',
    speaker: 'expert',
    persona: 'sabine',
    text: "Anything in equipment over five grand has to be capex for tax depreciation. If we dump that in 4711, workshop margins look terrible and accounting will chase us down at month-end.",
    germanText: "Alles über fünftausend Euro bei Ausrüstung muss steuerlich aktiviert werden. Wenn wir das in 4711 lassen, sieht die Werkstattmarge katastrophal aus und die Buchhaltung steht zum Monatsabschluss auf der Matte.",
    timestamp: '03:22',
    isGuardrail: true,
  },
  {
    id: 'd-3',
    speaker: 'agent',
    persona: 'apprentice',
    text: "Gotcha. What's the rule if an invoice arrives without an asset tag on it?",
    timestamp: '03:30',
    isGuardrail: true,
    questionContext: 'Missing asset tag rule',
  },
  {
    id: 'd-4',
    speaker: 'expert',
    persona: 'sabine',
    text: "Then don't touch it. If there's no asset tag or it's a vendor we don't know, stop right there and ping the plant controller.",
    germanText: "Dann Finger weg. Wenn keine Anlagennummer draufsteht oder der Lieferant unbekannt ist: sofort stoppen und den Werkscontroller anpingen.",
    timestamp: '03:41',
    isGuardrail: true,
  },
  {
    id: 'd-5',
    speaker: 'agent',
    persona: 'apprentice',
    text: "Saw you just put Delta Logistik on hold. What's the story with them?",
    timestamp: '07:48',
    isGuardrail: true,
    questionContext: 'Freezing December invoice',
  },
  {
    id: 'd-6',
    speaker: 'expert',
    persona: 'sabine',
    text: "Delta double-bills storage surcharges every December like clockwork. We freeze their freight bills until January credit reconciliation.",
    germanText: "Delta berechnet jeden Dezember wie ein Uhrwerk doppelte Lageraufschläge. Wir frieren deren Rechnungen bis zur Januar-Gutschrift ein.",
    timestamp: '07:58',
    isGuardrail: true,
  },
];
